### ISSUE TITLE
Broken link in peripheral devices

### ISSUE THREAD

**Issue by jonnew** [open-ephys/acq-board-docs#17]
I'm not sure where this should point to now:

https://github.com/open-ephys/acq-board-docs/blob/d3698c722236565020e9f3e84190fb3121339eba/source/User-Manual/Peripheral-devices.rst?plain=1#L69C32-L69C119

perhaps:

https://open-ephys.github.io/gui-docs/User-Manual/Plugins/OE-FPGA-Acquisition-Board.html#turning-on-aux-channels

Also, note that the build has a `linkcheck` target that can be used to check all for broken links like this.

**Comment by jsiegle** [comment]
Just fixed this and a few other broken links!
